//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessEntityAddress
    {
        public int BusinessEntityID { get; set; }
        public int AddressID { get; set; }
        public int AddressTypeID { get; set; }
        public System.Guid rowguid { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual BusinessEntity BusinessEntity { get; set; }
        public virtual BusinessEntity BusinessEntity1 { get; set; }
        public virtual AddressType AddressType { get; set; }
    }
}
